server:
  port: 8088

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:  jdbc:mysql://localhost:3306/book_borrow?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: "1234"
  redis:
    host: ${borrow.redis.host}
    port: ${borrow.redis.port}
    database: ${borrow.redis.database}
  jpa: # JPA相关配置（即使不用JPA，也需在此处禁用ddl-auto）
    hibernate:
     ddl-auto: none  # 禁用Hibernate自动建表（必须！避免与schema.sql冲突）
  sql: # SQL初始化配置（控制schema.sql/data.sql执行）
    init:
      mode: always  # 始终执行初始化（可选：always/embedded/never，开发环境用always，生产环境谨慎）

mybatis-plus:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity    # 实体类包（可选但建议）
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true


logging:
  level:
    com:
      example:
        mapper: debug
        service: info
        controller: info

borrow:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: borrow
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: adminToken

    user-secret-key: borrow
    user-ttl: 720000000
    user-token-name: userToken

    # 设置jwt签名加密时使用的秘钥
    employee-secret-key: borrow
    # 设置jwt过期时间
    employee-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    employee-token-name: employeeToken

    secret-key: borrow
    ttl: 720000
    token-name: token

  alioss:
    endpoint: ${borrow.alioss.endpoint}
    access-key-id: ${borrow.alioss.access-key-id}
    access-key-secret: ${borrow.alioss.access-key-secret}
    bucket-name: ${borrow.alioss.bucket-name}